spring:

  datasource:
    url: jdbc:h2:mem:taskList
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
  rsocket:
    server:
      port: 8080